if(NOT DEFINED CMOD_EXECUTABLE OR NOT DEFINED TEST_WORK_DIR)
    message(FATAL_ERROR "CMOD_EXECUTABLE and TEST_WORK_DIR are required")
endif()

file(MAKE_DIRECTORY "${TEST_WORK_DIR}")
if(NOT DEFINED TEST_CASE)
    set(TEST_CASE missing_project)
endif()
set(project "${TEST_WORK_DIR}/${TEST_CASE}.dissco")
set(expected "${TEST_CASE}.dissco")
set(expected_result 1)
set(expected_category "project")
set(command "${CMOD_EXECUTABLE}")
set(project_argument "${project}")
if(TEST_CASE STREQUAL "no_arguments")
    set(project_argument)
    set(expected "No project file was specified")
elseif(TEST_CASE STREQUAL "missing_project")
    # Leave the project absent.
else()
    file(READ "${PROJECT_FIXTURE}" xml)
    if(TEST_CASE STREQUAL "valid" OR TEST_CASE STREQUAL "valid_synthesis"
       OR TEST_CASE STREQUAL "valid_score")
        set(expected_result 0)
        if(TEST_CASE STREQUAL "valid_synthesis")
            string(REPLACE "<Synthesis>False</Synthesis>" "<Synthesis>True</Synthesis>" xml "${xml}")
        endif()
    elseif(TEST_CASE STREQUAL "malformed_xml")
        string(REPLACE "</ProjectRoot>" "" xml "${xml}")
        set(expected "byte")
    elseif(TEST_CASE STREQUAL "invalid_root")
        set(xml "<NotAProject/>")
        set(expected "ProjectRoot")
    elseif(TEST_CASE STREQUAL "missing_configuration")
        set(xml "<ProjectRoot/>")
        set(expected "ProjectConfiguration")
    elseif(TEST_CASE STREQUAL "missing_field")
        string(REPLACE "        <NumberOfChannels>2</NumberOfChannels>\n" "" xml "${xml}")
        set(expected "NumberOfChannels")
    elseif(TEST_CASE STREQUAL "invalid_integer")
        string(REPLACE "<SampleRate>44100</SampleRate>" "<SampleRate>44100oops</SampleRate>" xml "${xml}")
        set(expected "SampleRate")
    elseif(TEST_CASE STREQUAL "zero_threads")
        string(REPLACE "<NumberOfThreads>1</NumberOfThreads>" "<NumberOfThreads>0</NumberOfThreads>" xml "${xml}")
        set(expected "NumberOfThreads")
    elseif(TEST_CASE STREQUAL "invalid_boolean")
        string(REPLACE "<Synthesis>False</Synthesis>" "<Synthesis>Maybe</Synthesis>" xml "${xml}")
        set(expected "Synthesis")
    elseif(TEST_CASE STREQUAL "output_directory")
        string(REPLACE "<Synthesis>False</Synthesis>" "<Synthesis>True</Synthesis>" xml "${xml}")
        file(WRITE "${TEST_WORK_DIR}/SoundFiles" "This regular file blocks the output directory.")
        set(expected "SoundFiles")
        set(expected_category "output")
    elseif(TEST_CASE STREQUAL "children_without_layer")
        string(REPLACE "<Entry1>0</Entry1>\n                <Entry2/>"
                       "<Entry1>1</Entry1>\n                <Entry2/>" xml "${xml}")
        set(expected "NumberOfChildren")
    elseif(TEST_CASE STREQUAL "negative_children")
        string(REPLACE "<Entry1>0</Entry1>\n                <Entry2/>"
                       "<Entry1>-1</Entry1>\n                <Entry2/>" xml "${xml}")
        set(expected "NumberOfChildren")
    elseif(TEST_CASE STREQUAL "negative_fractional_children")
        string(REPLACE "<Entry1>0</Entry1>\n                <Entry2/>"
                       "<Entry1>-0.5</Entry1>\n                <Entry2/>" xml "${xml}")
        set(expected "NumberOfChildren")
    elseif(TEST_CASE STREQUAL "negative_duration")
        string(REPLACE "<Duration>1</Duration>" "<Duration>-1</Duration>" xml "${xml}")
        set(expected "ProjectConfiguration.Duration")
    elseif(TEST_CASE STREQUAL "empty_score")
        string(REPLACE "<Score>False</Score>" "<Score>True</Score>" xml "${xml}")
        set(expected "staff")
    elseif(TEST_CASE STREQUAL "lilypond")
        if(WIN32)
            set(ENV{PATH} "$ENV{SystemRoot}/System32;$ENV{SystemRoot}")
        else()
            set(ENV{PATH} "")
        endif()
        set(expected "LilyPond")
        set(expected_category "output")
    elseif(TEST_CASE STREQUAL "score_file")
        file(MAKE_DIRECTORY "${TEST_WORK_DIR}/score_file.ly")
        set(expected "score_file.ly")
        set(expected_category "output")
    else()
        message(FATAL_ERROR "Unknown test case: ${TEST_CASE}")
    endif()
    file(WRITE "${project}" "${xml}")
endif()
set(run_input "${TEST_WORK_DIR}/input.txt")
file(WRITE "${run_input}" "1\n")
file(GLOB previous_audio "${TEST_WORK_DIR}/SoundFiles/*.aiff")
list(LENGTH previous_audio previous_audio_count)
file(GLOB previous_scores "${TEST_WORK_DIR}/ScoreFiles/*.pdf")
list(LENGTH previous_scores previous_score_count)

execute_process(
    COMMAND ${command} ${project_argument}
    INPUT_FILE "${run_input}"
    WORKING_DIRECTORY "${TEST_WORK_DIR}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr
    TIMEOUT 10
)
file(WRITE "${TEST_WORK_DIR}/stdout.txt" "${stdout}")
file(WRITE "${TEST_WORK_DIR}/stderr.txt" "${stderr}")

if(expected_result EQUAL 0)
    if(NOT "${result}" STREQUAL "0" OR NOT stdout MATCHES "Build complete\\.")
        message(FATAL_ERROR "Valid project failed (${result}).\n${stdout}\n${stderr}")
    endif()
    if(TEST_CASE STREQUAL "valid_synthesis")
        file(GLOB audio "${TEST_WORK_DIR}/SoundFiles/*.aiff")
        list(LENGTH audio audio_count)
        math(EXPR expected_count "${previous_audio_count} + 1")
        if(NOT audio_count EQUAL expected_count)
            message(FATAL_ERROR "Successful synthesis did not produce one new audio file")
        endif()
    endif()
    if(TEST_CASE STREQUAL "valid_score")
        file(GLOB scores "${TEST_WORK_DIR}/ScoreFiles/*.pdf")
        list(LENGTH scores score_count)
        math(EXPR expected_count "${previous_score_count} + 1")
        if(NOT score_count EQUAL expected_count)
            message(FATAL_ERROR "Successful score output did not produce one new PDF")
        endif()
    endif()
elseif(NOT "${result}" STREQUAL "1"
       OR NOT stderr MATCHES "CMOD ${expected_category} error:"
       OR NOT stderr MATCHES "${expected}"
       OR NOT stderr MATCHES "Suggestion:"
       OR stdout MATCHES "Build complete\\.")
    message(FATAL_ERROR
        "${TEST_CASE} must produce an actionable ${expected_category} error (exit 1).\n"
        "Actual exit: ${result}\nstdout:\n${stdout}\nstderr:\n${stderr}")
endif()
